services:
  db:
    image: postgres:17.4
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 1s
      retries: 300
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_INITDB_ARGS: --data-checksums
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  db_data:
